# -*- coding: utf-8 -*-
"""Lista 1 - Lógica de Programação

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJU3nIdDdgRrl--s8H4zEmJEtRZnaSFJ
"""

# 1. Faça um programa mostre o seu primeiro nome na tela.

print("Thiago de Pádua")

# 2. Faça um programa que pede o primeiro nome do usuário e um sobrenome e mostra os dois nomes digitados na tela.

nome = input('Digite primeiro seu nome: ')
sobrenome = input('Digite seu sobrenome: ')
print(nome, sobrenome)

# 3. Faça um programa que mostra um X bem grande na tela, utilizando o print (um ou mais vezes). Obs.: esse X deverá ter, pelo menos altura de 7 caracteres. Desafio: fazer essa tarefa em um único print.

print('o     o')
print(' o   o')
print('  o o')
print('   o')
print('  o o')
print(' o   o')
print('o     o')

# 4. Faça um programa que pede o dia e mês de aniversário e diz quantos dias faltam para o aniversário, quantos dias se passaram do aniversário ou se hoje é o aniversário do usuário. (obs.: não utilize bibliotecas)

dia = int(input('Digite o dia de seu aniversário: '))
mes = int(input('Digite o mês de seu aniversário: '))
m = 'm'
s = 's'


if mes == 1:
    diff_dias = 60 + 32 - dia
    print(f"Passaram {diff_dias} dias de seu aniversário!")

elif mes == 2:
    diff_dias = 32 + 29 - dia
    print(f"Passaram {diff_dias} dias de seu aniversário!")

elif mes == 3:
    diff_dias = 33 - dia
    print(f"Passaram {diff_dias} dias de seu aniversário!")

elif mes == 4:
    diff_dias = dia - 2
    if diff_dias == 1:
        m = ''
        s = ''
    if diff_dias == 0:
        print("Feliz aniversário!")
    elif diff_dias > 0:
        print(f"Falta{m} {diff_dias} dia{s} para seu aniversário!")
    else:
        print(f"Passou {-1 * diff_dias} dia de seu aniversário!")

elif mes == 5:
    dias_faltantes = 28 + dia
    print(f'Faltam {dias_faltantes} dias para seu aniversário!')

elif mes == 6:
    dias_faltantes = 59 + dia  # 28(abril) + 31(maio) = 59
    print(f'Faltam {dias_faltantes} dias para seu aniversário!')

elif mes == 7:
    dias_faltantes = 89 + dia  # 28(abril) + 31(maio)  + 30(junho)= 89
    print(f'Faltam {dias_faltantes} dias para seu aniversário!')
elif mes == 8:
    dias_faltantes = 120 + dia  # 28(abril) + 31(maio)  + 30(junho) + 31(julho)= 120
    print(f'Faltam {dias_faltantes} dias para seu aniversário!')

elif mes == 9:
    dias_faltantes = 151 + dia
    print(f'Faltam {dias_faltantes} dias para seu aniversário!')

elif mes == 10:
    dias_faltantes = 181 + dia
    print(f'Faltam {dias_faltantes} dias para seu aniversário!')
elif mes == 11:
    dias_faltantes = 212 + dia
    print(f'Faltam {dias_faltantes} dias para seu aniversário!')

elif mes == 12:
    dias_faltantes = 242 + dia
    print(f'Faltam {dias_faltantes} dias para seu aniversário!')

else:
    print("Mês inválido")

# 5. Sua tarefa é criar um programa em Python que pede o preço original de um produto e dá 20% de desconto.

    # Você deve mostrar uma tabela contendo:
# a. Preço original do produto.
# b. Valor do desconto em R\$ (tipo 'Você ganho R$ xx,xx de desconto').
# c. Valor do produto com o desconto.

preco_original = float(input("Digite o preço original do produto: "))
desconto = preco_original * 0.20
preco_com_desconto = preco_original - desconto

print(f"Preço original: R${preco_original:.2f}")
print(f"Você ganhou R${desconto:.2f} de desconto.")
print(f"Preço com desconto: R${preco_com_desconto:.2f}")

# 6. Generalize o problema anterior, perguntando a porcentagem de desconto e mostrando os mesmos dados acima.

preco_original = float(input("Digite o preço original do produto: "))
percentual_desconto = float(input("Digite o percentual de desconto: ")) / 100
desconto = preco_original * percentual_desconto
preco_com_desconto = preco_original - desconto

print(f"Preço original: R${preco_original:.2f}")
print(f"Você ganhou R${desconto:.2f} de desconto.")
print(f"Preço com desconto: R${preco_com_desconto:.2f}")

# 7. Faça um programa que peça 3 valores e calcula sua média aritmética simples, mostrando esse resultado na tela.

a = float(input("Digite o primeiro valor: "))
b = float(input("Digite o segundo valor: "))
c = float(input("Digite o terceiro valor: "))

media = (a + b + c) / 3
print(f"A média aritmética é: {media:.2f}")

# 8. Faça um programa que peça 4 valores positivos e calcula:
    # a. A média aritmética simples.
    # b. A média geométrica.
    # c. A média harmônica

import math

a = float(input("Digite o primeiro valor: "))
b = float(input("Digite o segundo valor: "))
c = float(input("Digite o terceiro valor: "))
d = float(input("Digite o quarto valor: "))

# Média Aritmética
media_aritmetica = (a + b + c + d) / 4

# Média Geométrica
media_geometrica = (a * b * c * d) ** (1/4)

# Média Harmônica
media_harmonica = 4 / (1/a + 1/b + 1/c + 1/d)

print(f"Média Aritmética: {media_aritmetica:.2f}")
print(f"Média Geométrica: {media_geometrica:.2f}")
print(f"Média Harmônica: {media_harmonica:.2f}")

# 9. Faça um programa que peça 4 números reais e calcula:
    # a. A média aritmética simples.
    # b. A variância desses dados.
    # c. O desvio padrão desses dados.

import math

a = float(input("Digite o primeiro número real: "))
b = float(input("Digite o segundo número real: "))
c = float(input("Digite o terceiro número real: "))
d = float(input("Digite o quarto número real: "))

# Média Aritmética
media = (a + b + c + d) / 4

# Variância
variancia = ((a - media) ** 2 + (b - media) ** 2 + (c - media) ** 2 + (d - media) ** 2) / 4

# Desvio Padrão
desvio_padrao = math.sqrt(variancia)

print(f"Média Aritmética: {media:.2f}")
print(f"Variância: {variancia:.2f}")
print(f"Desvio Padrão: {desvio_padrao:.2f}")

# 10. Faça um programa que, dados 3 números inteiros, mostre na tela o maior deles.

a = int(input("Digite o primeiro número inteiro: "))
b = int(input("Digite o segundo número inteiro: "))
c = int(input("Digite o terceiro número inteiro: "))

maior = max(a, b, c)
print(f"O maior número é: {maior}")

# 11. Faça um programa que, dados 3 números inteiros, mostre na tela esses números em ordem crescente.

a = int(input("Digite o primeiro número inteiro: "))
b = int(input("Digite o segundo número inteiro: "))
c = int(input("Digite o terceiro número inteiro: "))

numeros = [a, b, c]
numeros.sort()

print(f"Os números em ordem crescente são: {numeros}")

# 12. Faça um programa que, dados 3 strings, mostra essas strings em ordem alfabética.

a = input("Digite a primeira string: ")
b = input("Digite a segunda string: ")
c = input("Digite a terceira string: ")

strings = [a, b, c]
strings.sort()

print(f"As strings em ordem alfabética são: {strings}")

# 13. Faça um programa que peça a informação se o usuário é homem ou mulher, o peso, a altura e a idade e mostre na tela o TMB em calorias.
# A Taxa Metabólica Basal (TMB) é a quantidade mínima de energia que o corpo precisa para manter as funções vitais, como respiração, circulação e temperatura corporal, em repouso. A TMB representa cerca de 60% a 70% do gasto energético total diário de uma pessoa e varia de acordo com o sexo, a idade, o peso e a altura.

    # Para calcular a TMB manualmente, você deve usar as seguintes fórmulas da equação de Harris-Benedict:
    # Para homens: TMB = 66,47 + (13,75 x peso em kg) + (5,003 x altura em cm) - (6,755 x idade em anos)
    # Para mulheres: TMB = 655,09 + (9,563 x peso em kg) + (1,85 x altura em cm) - (4,676 x idade em anos)

sexo = input("Digite seu sexo (homem/mulher): ").lower()
peso = float(input("Digite seu peso (kg): "))
altura = float(input("Digite sua altura (cm): "))
idade = int(input("Digite sua idade (anos): "))

if sexo == "homem":
    tmb = 66.47 + (13.75 * peso) + (5.003 * altura) - (6.755 * idade)
else:
    tmb = 655.09 + (9.563 * peso) + (1.85 * altura) - (4.676 * idade)

print(f"Sua TMB é: {tmb:.2f} calorias/dia")

# 14. Faça um programa que peça um número inteiro para o usuário e mostra a tabuada desse número.

numero = int(input("Digite um número inteiro: "))

for i in range(1, 11):
    print(f"{numero} x {i} = {numero * i}")